### ISSUE TITLE
TODO list - update

### ISSUE THREAD

**Issue by B176888-2020** [B176888-2020/Assignment1#1]
TODO list - Basic:
- [x] Quality check (2020.10.17)
- [x] Analyse the QC result (2020.10.17)
- [x] Paired alignment and SAM > BAM transformation (2020.10.17)
- [x] Generate counts data (2020.10.18)
- [x] Clean the pseduogene (2020.10.18)
- [x] Loops for multi-samples (2020.10.18)
- [x] Generate a single tsv (but txt) output file (2020.10.18)
- [x] Comments check and Documentation(2020.10.18)
- [x] Get everything Done, Remember to use the ABSOLUTE PATH for the documents and clean the repo (2020.10.19)
- [x] Pass the final test and find bugs (2020.10.19)
- [ ] write the Report for the assignment and Upload docs to Learn. (2020.10.22)

TODO list - Advance
- [x] make sh a program like bowtie2 that could be used as a user-friendly command.
- [x] make the directory relationship more clear during the processing. (2020.10.18)
- [x] More precise usage of options and improve the performances. (2020.10.19)
- [x] Possible Pararleller(2020.10.18)
- [x] Improve the Performance and Clean Code (2020.10.19)
- [ ] README but in the report (2020.20) will be updated to the README file.
- [x] More user-friendly notations(2020.10.21)
- [x] Comments FINAL proofread (2020.10.21)
